#!/bin/bash

if [ -d ~/Desktop/ns-3 ]
then
	cd ~/Desktop/ns-3
else
	cd ~/ns-3
fi

if [ -d stratos ]
then
	rm stratos/centralized*.txt
else
	mkdir stratos
fi

#Default = NO LOGGING
export NS_LOG=

#Search, Schedule and Service apps logging
#export NS_LOG="SearchApplication=*|prefix_func:ServiceApplication=*|prefix_func:CentralApplication=*|prefix_func:ScheduleApplication=*|prefix_func"

#Full Stratos logging
#export NS_LOG="SearchApplication:ServiceApplication:CentralApplication:ScheduleApplication:OntologyApplication:PositionApplication:ResultsApplication:RouteApplication:Stratos"

./waf clean
# Configure and complite first the program to avoid counting compilation time as running time
# Use debug if you want to see log output
#CXXFLAGS="-O3 -w" ./waf configure --build-profile=debug --enable-static
CXXFLAGS="-O3 -w" ./waf configure --build-profile=optimized --enable-static

# Build once
./waf --run stratos_centralized

for i in {1..2}
do
	./waf --run "stratos_centralized --nSchedule=1" >> stratos/centralized_schedule_1.txt
 	./waf --run "stratos_centralized --nSchedule=2" >> stratos/centralized_schedule_2.txt
 	./waf --run "stratos_centralized --nSchedule=3" >> stratos/centralized_schedule_3.txt
 	./waf --run "stratos_centralized --nSchedule=4" >> stratos/centralized_schedule_4.txt
 	./waf --run "stratos_centralized --nSchedule=5" >> stratos/centralized_schedule_5.txt

	./waf --run "stratos_centralized --nMobile=0" >> stratos/centralized_mobile_0.txt
	./waf --run "stratos_centralized --nMobile=25" >> stratos/centralized_mobile_25.txt
	./waf --run "stratos_centralized --nMobile=50" >> stratos/centralized_mobile_50.txt
	./waf --run "stratos_centralized --nMobile=100" >> stratos/centralized_mobile_100.txt

	./waf --run "stratos_centralized --nRequesters=1" >> stratos/centralized_requesters_1.txt
	./waf --run "stratos_centralized --nRequesters=2" >> stratos/centralized_requesters_2.txt
	./waf --run "stratos_centralized --nRequesters=4" >> stratos/centralized_requesters_4.txt
	./waf --run "stratos_centralized --nRequesters=8" >> stratos/centralized_requesters_8.txt
	./waf --run "stratos_centralized --nRequesters=16" >> stratos/centralized_requesters_16.txt
	./waf --run "stratos_centralized --nRequesters=24" >> stratos/centralized_requesters_24.txt
	./waf --run "stratos_centralized --nRequesters=32" >> stratos/centralized_requesters_32.txt

	./waf --run "stratos_centralized --nServices=1" >> stratos/centralized_services_1.txt
	./waf --run "stratos_centralized --nServices=2" >> stratos/centralized_services_2.txt
	./waf --run "stratos_centralized --nServices=4" >> stratos/centralized_services_4.txt
	./waf --run "stratos_centralized --nServices=8" >> stratos/centralized_services_8.txt

	#./waf --run "stratos_centralized --nPackets=1" >> stratos/centralized_packets_1.txt
	./waf --run "stratos_centralized --nPackets=10" >> stratos/centralized_packets_10.txt
	./waf --run "stratos_centralized --nPackets=20" >> stratos/centralized_packets_20.txt
	./waf --run "stratos_centralized --nPackets=40" >> stratos/centralized_packets_40.txt
	./waf --run "stratos_centralized --nPackets=60" >> stratos/centralized_packets_60.txt
done