#!/bin/bash

if [ -d ~/Desktop/ns-3 ]
then
	cd ~/Desktop/ns-3
else
	cd ~/ns-3
fi

if [ -d stratos ]
then
	rm stratos/centralized*.txt
else
	mkdir stratos
fi

#Default = NO LOGGING
export NS_LOG=

#Search, Schedule and Service apps logging
#export NS_LOG="SearchApplication=*|prefix_func:ServiceApplication=*|prefix_func:CentralApplication=*|prefix_func:ScheduleApplication=*|prefix_func"

#Full Stratos logging
#export NS_LOG="SearchApplication:ServiceApplication:CentralApplication:ScheduleApplication:OntologyApplication:PositionApplication:ResultsApplication:RouteApplication:Stratos"

# Configure and complite first the program to avoid counting compilation time as running time
./waf clean
CXXFLAGS="-O3 -w" ./waf -d optimized configure --enable-static --enable-examples

# Build once
./waf --run stratos_centralized

for i in {1..100}
do
	./waf --run "stratos_centralized --nMobile=0" >> stratos/centralized_mobile_0.txt 2>&1
	./waf --run "stratos_centralized --nMobile=25" >> stratos/centralized_mobile_25.txt 2>&1
	./waf --run "stratos_centralized --nMobile=50" >> stratos/centralized_mobile_50.txt 2>&1
	./waf --run "stratos_centralized --nMobile=100" >> stratos/centralized_mobile_100.txt 2>&1

	./waf --run "stratos_centralized --nRequesters=1" >> stratos/centralized_requesters_1.txt 2>&1
	./waf --run "stratos_centralized --nRequesters=2" >> stratos/centralized_requesters_2.txt 2>&1
	./waf --run "stratos_centralized --nRequesters=4" >> stratos/centralized_requesters_4.txt 2>&1
	./waf --run "stratos_centralized --nRequesters=8" >> stratos/centralized_requesters_8.txt 2>&1
	./waf --run "stratos_centralized --nRequesters=16" >> stratos/centralized_requesters_16.txt 2>&1
	./waf --run "stratos_centralized --nRequesters=24" >> stratos/centralized_requesters_24.txt 2>&1
	./waf --run "stratos_centralized --nRequesters=32" >> stratos/centralized_requesters_32.txt 2>&1

	./waf --run "stratos_centralized --nServices=1" >> stratos/centralized_services_1.txt 2>&1
	./waf --run "stratos_centralized --nServices=2" >> stratos/centralized_services_2.txt 2>&1
	./waf --run "stratos_centralized --nServices=4" >> stratos/centralized_services_4.txt 2>&1
	./waf --run "stratos_centralized --nServices=8" >> stratos/centralized_services_8.txt 2>&1

	#./waf --run "stratos_centralized --nPackets=1" >> stratos/centralized_packets_1.txt 2>&1
	./waf --run "stratos_centralized --nPackets=10" >> stratos/centralized_packets_10.txt 2>&1
	./waf --run "stratos_centralized --nPackets=20" >> stratos/centralized_packets_20.txt 2>&1
	./waf --run "stratos_centralized --nPackets=40" >> stratos/centralized_packets_40.txt 2>&1
	./waf --run "stratos_centralized --nPackets=60" >> stratos/centralized_packets_60.txt 2>&1
done